### ISSUE TITLE
README.md - NodeJS packages

### ISSUE THREAD

**Issue by tti0** [palkerecsenyi/grammarer#2]
Tested on Raspberry Pi 3 - Raspbian Stretch.
It is not entirely obvious that one must install the NPM `css` and `mongodb` modules. Indeed, I had to look at ll. 1-3 of https://github.com/palkerecsenyi/grammarer/blob/master/setup.js to work this out.
Perhaps add instructions to do this in the README.md, or add a friendlier error message, rather than:
```
internal/modules/cjs/loader.js:596
    throw err;
    ^
Error: Cannot find module 'css'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/grammarer/setup.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```
with instructions as to what to do to fix the error.

**Comment by palkerecsenyi** [comment]
Thanks. I will add the instruction `npm install` into the starting guide.  I forgot about this, sorry.

**Comment by palkerecsenyi** [comment]
Fixed
